// This file is autogenerated by CMake. Do not edit.

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>


QT_DECLARE_EXTERN_RESOURCE(qmlcache_Myst);
QT_DECLARE_EXTERN_RESOURCE(qmake_Myst);
QT_DECLARE_EXTERN_RESOURCE(Myst_raw_qml_0);


QT_DECLARE_EXTERN_SYMBOL_VOID(qml_register_types_Myst);

class MystPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    MystPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {

QT_KEEP_SYMBOL(qml_register_types_Myst);
QT_KEEP_RESOURCE(qmlcache_Myst);
QT_KEEP_RESOURCE(qmake_Myst);
QT_KEEP_RESOURCE(Myst_raw_qml_0);
    }
};



#include "Mystplugin_MystPlugin.moc"
